language: r

r_github_packages:
    - jimhester/covr
    - berndbischl/ParamHelpers
    - mlr-org/farff
    - mlr-org/mlr
apt_packages:
    - r-cran-rjava
r_binary_packages:
    - testthat
    - knitr
after_success:
  - Rscript -e 'library(covr);coveralls()'
before_script:
    - sudo R CMD javareconf
notifications:
  email:
    recipients:
        - michellang@gmail.com
        - bernd_bischl@gmx.net
    on_success: change
    on_failure: always

env:
  global:
    secure: FXpyq4vsM7ZUV83Jxq7rtSCFjVfJ2kx6uPBocHfTm/ZMHfjvqHux+Uk2gX0ei8gUSC6iMLEolagwbOLIIPpQfCfjBQa+KEto4GW+cPNnTXEZBtiNiVDeBq3nsLGFY05Ojo/SK5Ign50fTPRZvfzPiAqVMVeruwKA9rVLknv2dSg=
