language: r
sudo: false
r_check_args: "--as-cran --run-donttest"

env:
  global:
  - secure: oBSw3lt+e3/iEEhYHXEAJpZWmITbC6HtqRVXIKQsVpaGfQ6zxxoIKeUOpSUGSGvG+CLBqie97a7eWDq2Z21md6wr+jBnmAoHlrUckQdw7GF8aT3aOmZzQ6cZbQniTn5nRJ8GlfYi/nkhxIDQ0bUY3KBBUak27uHvNEY4wqSdCxE=
  - secure: "UOXrFQRyK/l9AUBxpoEq3DkOaBGmml+gChxwla8Y9Z5xacCM46DhY2yob5BSqtD1EI+aKGe/1WwN/dqPeuJhwSSPFggP+RJ26Kyf8jWSxHPbZSOsULGVcfgtl/kgozlrj8alG26WUjcbA+c7GlvbSZXu3OWRZHW0aTnx9IIda+A="

r_github_packages:
    - jimhester/covr
    - mlr-org/farff
    - mlr-org/mlr
    - berndbischl/BBmisc
    - berndbischl/ParamHelpers

cache:
  packages: true
  directories:
    - $HOME/.openml/cache

before_script:
  - mkdir -p "$HOME/.openml/cache" && find "$HOME/.openml/cache"
  - echo "apikey=$OPENMLAPIKEY" > "$HOME/.openml/config"

after_success:
  - Rscript -e 'library(covr);coveralls()'
  # now build vignette
  - git checkout master
  # do we need this? See also last line here
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  # build PDF vignette
  - R --no-save <<< 'library("rmarkdown"); render("vignettes/OpenML.Rmd", "pdf_document")'
  # store git credentials and setup git
  - git config user.name $GN
  - git config user.email $GM
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GT:@github.com" >> .git/credentials
  - git config push.default matching
  # push PDF vignette to repo and skip continuous integration for this build
  - git add vignettes/OpenML.pdf
  - git commit vignettes -m "update auto-generated vignettes [ci skip]" || true
  - git push
  # do we need this?
  - "[ $TRAVIS_PULL_REQUEST == \"false\" -a $TRAVIS_BRANCH == \"master\" ] && curl -s -X POST -H \"Content-Type:application/json\" -H \"Accept:application/json\" -H \"Travis-API-Version:3\" -H \"Authorization:token $TT\" -d \"{\\\"request\\\":{\\\"branch\\\":\\\"gh-pages\\\", \\\"message\\\":\\\"commit $TRAVIS_COMMIT $TRAVIS_COMMIT_MSG\\\"}}\" https://api.travis-ci.org/repo/mlr-org%2Fmlr-tutorial/requests"

notifications:
  email:
    recipients:
        - michellang@gmail.com
        - bernd_bischl@gmx.net
        - j.bossek@gmail.com
    on_success: change
    on_failure: always
  slack: openml:sHBAXvEJBWpSluiYfzSogNFT#buildnotifications
