language: r

r_github_packages:
    - jimhester/covr
    - berndbischl/ParamHelpers
    - mlr-org/farff
    - mlr-org/mlr
apt_packages:
    - r-cran-rjava
r_binary_packages:
    - testthat
    - knitr
after_success:
  - Rscript -e 'library(covr);coveralls()'
before_script:
    - sudo R CMD javareconf
notifications:
  email:
    recipients:
        - michellang@gmail.com
        - bernd_bischl@gmx.net
    on_success: change
    on_failure: always

env:
  global:
  - secure: oBSw3lt+e3/iEEhYHXEAJpZWmITbC6HtqRVXIKQsVpaGfQ6zxxoIKeUOpSUGSGvG+CLBqie97a7eWDq2Z21md6wr+jBnmAoHlrUckQdw7GF8aT3aOmZzQ6cZbQniTn5nRJ8GlfYi/nkhxIDQ0bUY3KBBUak27uHvNEY4wqSdCxE=
   
