language: r

r_github_packages:
    - jimhester/covr
    - mlr-org/farff
apt_packages:
    - r-cran-rjava
r_binary_packages:
    - testthat
    - knitr
after_success:
  - Rscript -e 'library(covr);coveralls()'
before_script:
    - sudo R CMD javareconf
notifications:
  email:
    recipients:
        - michellang@gmail.com
        - bernd_bischl@gmx.net
    on_success: change
    on_failure: always
